
services:
  - type: web
    name: eliteflix
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: NODE_VERSION
        value: 20.19.5
      - key: SESSION_SECRET
        generateValue: true
